// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Dashboard.tsx": () => import("../components/mockups/Dashboard.tsx"),
  "./components/mockups/ScreenshotsGallery.tsx": () => import("../components/mockups/ScreenshotsGallery.tsx"),
  "./components/mockups/TimelineView.tsx": () => import("../components/mockups/TimelineView.tsx")
};
