import {
  pgTable,
  uuid,
  text,
  timestamp,
  pgEnum,
  jsonb,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { companiesTable } from "./companies";

export const userRoleEnum = pgEnum("user_role", [
  "super_user",
  "company_admin",
  "team_member",
  "manager",
]);

export const usersTable = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  role: userRoleEnum("role").notNull().default("team_member"),
  // Tenant this user belongs to. NULL only for Super Users (the SaaS owner),
  // who live above all tenants. Enforced non-null for every other role by app
  // logic + backfill.
  companyId: uuid("company_id").references(() => companiesTable.id, {
    onDelete: "cascade",
  }),
  managedById: uuid("managed_by_id"),
  // Per-page console permissions assigned by the Company Admin when creating
  // managers / team members. Keys are dashboard page ids (e.g. "devices"),
  // values are "view" | "edit". NULL means "no restriction" (full role-based
  // access, which is also the case for company_admin and super_user).
  pagePermissions: jsonb("page_permissions").$type<Record<
    string,
    "view" | "edit"
  > | null>(),
  selfDashboardEnabled: text("self_dashboard_enabled").notNull().default("true"),
  // One-time "forgot password" reset code, generated by an admin and handed to
  // the user out-of-band (no email service). Stored only as a SHA-256 hash;
  // NULL when no reset is pending. Cleared on use or overwrite.
  resetCodeHash: text("reset_code_hash"),
  resetCodeExpiresAt: timestamp("reset_code_expires_at", {
    withTimezone: true,
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const usersRelations = relations(usersTable, ({ one, many }) => ({
  managedBy: one(usersTable, {
    fields: [usersTable.managedById],
    references: [usersTable.id],
    relationName: "manager",
  }),
  reports: many(usersTable, { relationName: "manager" }),
}));

export const insertUserSchema = createInsertSchema(usersTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof usersTable.$inferSelect;
export type UserRole = (typeof userRoleEnum.enumValues)[number];
